"""match_block_page() / parse_http_response() unit tests.

These cover the --verify active-probe logic, including the two real traps
found in the field: FortiWeb's <title> sitting at the END of a 39KB body,
and FortiWeb's localized Indonesian title.
"""

from __future__ import annotations

from w4f.scanner import match_block_page, parse_http_response


def _fortiweb_body_en(title=" The URL you requested has been blocked "):
    # ~39KB of filler with the title near the end — the real observed shape
    # (FortiWeb HTML4 block page).
    filler = b"x" * 38000
    return filler + f"<html><head><title>{title}</title></head><body>block</body></html>".encode()


def _fortiweb_body_id():
    return _fortiweb_body_en(title=" The URL Request Tidak Tersedia ")


class TestMatchFortiWeb:
    def test_english_title(self):
        body = _fortiweb_body_en()
        parsed = parse_http_response(b"HTTP/1.1 500 Internal Server Error\r\n\r\n" + body)
        got = match_block_page(parsed["title"], parsed["head_text"],
                               parsed["body_text"], parsed["status"])
        assert got == {"vendor": "fortiweb", "title": "The URL you requested has been blocked",
                       "status": "HTTP/1.1 500 Internal Server Error"}

    def test_localized_id_title(self):
        body = _fortiweb_body_id()
        parsed = parse_http_response(b"HTTP/1.1 500 Internal Server Error\r\n\r\n" + body)
        got = match_block_page(parsed["title"], parsed["head_text"],
                               parsed["body_text"], parsed["status"])
        assert got and got["vendor"] == "fortiweb"
        assert "Tidak Tersedia" in got["title"]

    def test_title_far_in_body(self):
        # Regression: the original probe read only 4KB after the header and
        # missed titles past that. parse_http_response must find it anywhere
        # in the first 64KB.
        parsed = parse_http_response(b"HTTP/1.1 500 Internal Server Error\r\n\r\n"
                                     + _fortiweb_body_en())
        assert "has been blocked" in parsed["title"]


class TestMatchOther:
    def test_f5_request_rejected(self):
        parsed = parse_http_response(
            b"HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n"
            b"<html><head><title>Request Rejected</title></head></html>"
        )
        got = match_block_page(parsed["title"], parsed["head_text"],
                               parsed["body_text"], parsed["status"])
        assert got and got["vendor"] == "f5-asm"

    def test_cloudflare_attention_required(self):
        parsed = parse_http_response(
            b"HTTP/1.1 403 Forbidden\r\nServer: cloudflare\r\n\r\n"
            b"<html><head><title>Attention Required! | Cloudflare</title></head>"
            b"<body>cloudflare</body></html>"
        )
        got = match_block_page(parsed["title"], parsed["head_text"],
                               parsed["body_text"], parsed["status"])
        assert got and got["vendor"] == "cloudflare"

    def test_imperva_incapsula_body(self):
        parsed = parse_http_response(
            b"HTTP/1.1 403 Forbidden\r\n\r\n"
            b"<html>Request blocked by Incapsula</html>"
        )
        got = match_block_page(parsed["title"], parsed["head_text"],
                               parsed["body_text"], parsed["status"])
        assert got and got["vendor"] == "imperva"

    def test_no_match_plain_page(self):
        parsed = parse_http_response(
            b"HTTP/1.1 200 OK\r\nServer: nginx\r\n\r\n<html><title>Login</title></html>"
        )
        assert match_block_page(parsed["title"], parsed["head_text"],
                                parsed["body_text"], parsed["status"]) is None

    def test_aws_waf_block_page(self):
        # CloudFront + AWS WAF block page: "ERROR: The request could not be
        # satisfied" / "Request blocked" (seen on a bank's API host,
        # example-hospital.com). body_text is lowercased by parse_http_response,
        # so the marker match is case-insensitive here too.
        body = ("<html><head><title>ERROR: The request could not be satisfied"
                "</title></head><body>Request blocked. We can't connect to "
                "the server for this app or website at this time. There might "
                "be too much traffic or a configuration error. <p>Generated by "
                "cloudfront (CloudFront)</p></body></html>")
        got = match_block_page("ERROR: The request could not be satisfied",
                               "<title>ERROR</title>", body.lower(), "HTTP/2 403")
        assert got and got["vendor"] == "aws-waf"

    def test_aws_waf_not_matched_without_markers(self):
        body = "<html><head><title>404 Not Found</title></head></html>"
        got = match_block_page("404 Not Found", "<title>404</title>", body, "HTTP/2 404")
        assert got is None

    def test_aws_waf_cloudfront_block(self):
        # Real block page observed on a bank's API host (AWS WAF via
        # CloudFront): 403, CloudFront error title, "Request blocked." body.
        parsed = parse_http_response(
            b"HTTP/1.1 403 Forbidden\r\nServer: CloudFront\r\n"
            b"X-Cache: Error from cloudfront\r\n\r\n"
            b'<!doctype html><html><head>'
            b"<title>ERROR: The request could not be satisfied</title></head>"
            b"<body><h1>403 ERROR</h1><h2>The request could not be satisfied.</h2>"
            b"<p>Request blocked.</p>Generated by cloudfront (CloudFront)</body></html>"
        )
        got = match_block_page(parsed["title"], parsed["head_text"],
                               parsed["body_text"], parsed["status"])
        assert got and got["vendor"] == "aws-waf"
        assert got["status"] == "HTTP/1.1 403 Forbidden"

    def test_cloudfront_generic_error_not_waf(self):
        # Same CloudFront error title but a NON-block reason ("Bad request.")
        # is an ordinary CloudFront 4xx, not a WAF block — must not match.
        parsed = parse_http_response(
            b"HTTP/1.1 400 Bad Request\r\nServer: CloudFront\r\n\r\n"
            b"<html><head><title>ERROR: The request could not be satisfied</title>"
            b"</head><body><h1>400 ERROR</h1><p>Bad request.</p>"
            b"Generated by cloudfront (CloudFront)</body></html>"
        )
        assert match_block_page(parsed["title"], parsed["head_text"],
                                parsed["body_text"], parsed["status"]) is None

    def test_akamai_kona_access_denied(self):
        parsed = parse_http_response(
            b"HTTP/1.1 403 Forbidden\r\nServer: AkamaiGHost\r\n\r\n"
            b"<html><head><title>Access Denied</title></head>"
            b"<body>You don't have permission to access this. "
            b"Generated by Akamai.</body></html>"
        )
        got = match_block_page(parsed["title"], parsed["head_text"],
                               parsed["body_text"], parsed["status"])
        assert got and got["vendor"] == "akamai"

    def test_sucuri_firewall_block(self):
        parsed = parse_http_response(
            b"HTTP/1.1 403 Forbidden\r\nServer: Sucuri/Cloudproxy\r\n\r\n"
            b"<html><head><title>Blocked</title></head>"
            b"<body>Sucuri Firewall - Blocked. Your request has been blocked."
            b"</body></html>"
        )
        got = match_block_page(parsed["title"], parsed["head_text"],
                               parsed["body_text"], parsed["status"])
        assert got and got["vendor"] == "sucuri"

    def test_wordfence_block(self):
        parsed = parse_http_response(
            b"HTTP/1.1 403 Forbidden\r\nServer: nginx\r\n\r\n"
            b"<html><head><title>403 Forbidden</title></head>"
            b"<body>This response was generated by Wordfence.</body></html>"
        )
        got = match_block_page(parsed["title"], parsed["head_text"],
                               parsed["body_text"], parsed["status"])
        assert got and got["vendor"] == "wordfence"

    def test_wallarm_block(self):
        parsed = parse_http_response(
            b"HTTP/1.1 403 Forbidden\r\nServer: nginx\r\n\r\n"
            b"<html><head><title>Forbidden</title></head>"
            b"<body>Request blocked by Wallarm: input validation failed."
            b"</body></html>"
        )
        got = match_block_page(parsed["title"], parsed["head_text"],
                               parsed["body_text"], parsed["status"])
        assert got and got["vendor"] == "wallarm"


class TestParseHttpResponse:
    def test_headers_lowercased_and_split(self):
        data = (
            b"HTTP/1.1 302 Found\r\n"
            b"Server: nginx\r\n"
            b"X-Custom: a:b\r\n"
            b"Set-Cookie: a=1; Path=/\r\n"
            b"Set-Cookie: b=2\r\n\r\n"
            b"<html></html>"
        )
        p = parse_http_response(data)
        assert p["status"] == "HTTP/1.1 302 Found"
        assert p["headers"]["server"] == "nginx"
        assert p["headers"]["x-custom"] == "a:b"
        assert p["set-cookie-list"] == ["a=1; Path=/", "b=2"]

    def test_empty_data(self):
        p = parse_http_response(b"")
        assert p["status"] == ""
        assert p["headers"] == {}


class TestPathInterception:
    """A TLS-inspection middlebox on the SCANNER's path must never be
    reported as the target's edge — that would fingerprint our own network
    on every host we scan."""

    def test_fortinet_webfilter_page_is_flagged_as_interception(self):
        from w4f.scanner import match_block_page
        body = ("<h1>fortinet webfilter</h1><h3>this connection is invalid. "
                "ssl certificate expired.</h3><p>a secure connection to "
                "example.com cannot be established.</p>")
        out = match_block_page("Invalid Connection", "", body, "HTTP/1.1 403 Forbidden")
        assert out and out["interception"] is True
        assert out["vendor"] == "fortinet-webfilter"

    def test_generic_invalid_connection_is_not_matched(self):
        # the title alone is too generic — the vendor marker must be present
        from w4f.scanner import match_block_page
        assert match_block_page("Invalid Connection", "", "<p>try again</p>",
                                "HTTP/1.1 403 Forbidden") is None

    def test_inspection_ca_issuer_detected(self):
        from w4f.scanner import detect_interception
        cert = {"issuer_org": "Fortinet",
                "issuer": "countryName=US, organizationName=Fortinet, "
                          "organizationalUnitName=Certificate Authority, "
                          "commonName=FG4H0FT922903229"}
        out = detect_interception(cert)
        assert out and out["by"] == "fortinet"
        assert "Fortinet" in out["evidence"]

    def test_public_ca_is_not_interception(self):
        from w4f.scanner import detect_interception
        for org in ("DigiCert Inc", "Let's Encrypt", "GlobalSign nv-sa",
                    "Sectigo Limited", "Google Trust Services"):
            assert detect_interception({"issuer_org": org, "issuer": org}) is None

    def test_interception_page_never_becomes_a_block_finding(self):
        # `block` feeds --csv/--sarif as a finding ABOUT THE HOST; an
        # interception page is a fact about our own path instead
        from w4f.scanner import match_block_page
        out = match_block_page("Invalid Connection", "",
                               "<h1>fortinet webfilter</h1>", "HTTP/1.1 403 Forbidden")
        assert out.get("interception") is True


class TestPassiveBlockPage:
    def test_block_page_on_a_normal_request_is_matched(self):
        # a WAF that blocks the PLAIN GET already handed us its page; the
        # vendor should not require --verify to be named
        from w4f.scanner import match_block_page
        out = match_block_page("The URL you requested has been blocked", "",
                               "<html>blocked</html>", "HTTP/1.1 403 Forbidden")
        assert out and out["vendor"] == "fortiweb"


class TestImpervaSecureSphere:
    """The on-prem appliance serves a different page from Incapsula/cloud —
    and answers 200 OK, so only --verify reaches it."""

    def test_securesphere_error_page(self):
        from w4f.scanner import match_block_page
        body = ("<html><head><title>error</title></head><body>"
                "this page can't be displayed. contact your support team. "
                "the incident id is: 1234567890.</body></html>")
        out = match_block_page("Error", "", body, "HTTP/1.1 200 OK")
        assert out and out["vendor"] == "imperva"

    def test_securesphere_contact_support_variant(self):
        from w4f.scanner import match_block_page
        body = ("<title>error</title>the incident id is: 99. "
                "contact support for additional information.")
        assert match_block_page("Error", "", body, "HTTP/1.1 200 OK")["vendor"] == "imperva"

    def test_generic_error_title_alone_is_not_a_block(self):
        from w4f.scanner import match_block_page
        assert match_block_page("Error", "", "<p>something went wrong</p>",
                                "HTTP/1.1 500 Internal Server Error") is None

    def test_incident_id_alone_is_not_enough(self):
        # an application error page may print an incident id of its own
        from w4f.scanner import match_block_page
        assert match_block_page("Oops", "", "your incident id is 42, sorry",
                                "HTTP/1.1 500 Internal Server Error") is None
