"""akamai — cdn vendor signature. See _template.py for the schema."""

VENDOR = {'name': 'akamai',
 'headers': {'server': 'akamai',
             'x-akamai': None,
             'x-akamai-transformed': None,
             'akamai-grn': None,
             'x-grn': None,
             'akamai-request-bc': None},
 'cookies': ['^ak_bmsc=',
             '^bm_sz=',
             '^akavpau_',
             '^_abck=',
             '^aka~',
             '^akaalb_',
             '^ak_bmsc=[^;]*;\\s*.*\\bE3D='],
 'cert': 'akamai',
 'cname': 'akamaized|akamaihd|edgesuite|akadns|akamai\\.net',
 'ptr': 'akamai',
 'nets': ['23.32.0.0/11',
          '104.64.0.0/10',
          '184.24.0.0/13',
          '2.16.0.0/13',
          '23.192.0.0/11',
          '96.6.0.0/15',
          '96.7.0.0/16']}
